name: "wifilink2-test"
author: "OlegKiko"
description: "Runcam wifilink2 test preset"
category: "FPV"
sensor: ""  # Set sensor file if needed
status: "Community"
tags: ["runcam","wifilink2"]
files:
  wfb.conf:
    bandwidth: "20"
    channel: "160"
    txpower: "1"
    stbc: "0"
    ldpc: "0"
    mcs_index: "1"
    fec_k: "8"
    fec_n: "12"
  telemetry.conf:
    serial: "/dev/ttyS2"
    baud: "57600"
    router: "0"
  majestic.yaml:
    fpv.enabled: "false"
    video0.codec: "h265"
    video0.fps: "60"
    video0.bitrate: "4096"
    video0.size: "1280x720"
    audio.enabled: "false"
    
    
additional_files:
  - txprofiles.conf
    
