name: "wifilink2-test"
author: "OlegKiko"
description: "Runcam wifilink2 test preset"
category: "FPV"
sensor: ""  # Set sensor file if needed
status: "Community"
tags: ["runcam","wifilink2"]
files:
  wfb.conf:
    wireless.width: "20"
    wireless.channel: 161
    wireless.txpower: "1"
    broadcast.stbc: "0"
    broadcast.ldpc: "0"
    broadcast.mcs_index: "1"
    #broadcast.tun_index: "1"
    broadcast.fec_k: "8"
    broadcast.fec_n: "12"
  telemetry.conf:
    telemetry.serial: ttyS2
    telemetry.baud: "57600"
    telemetry.router: mavfwd
  majestic.yaml:
    fpv.enabled: "false"
    video0.codec: "h265"
    video0.fps: "60"
    video0.bitrate: "4096"
    video0.size: "1280x720"
    audio.enabled: "false"
    
    
additional_files:
  - txprofiles.conf
    
